apiVersion: monitoring.elostech.cz/v1alpha1
kind: Grafana
metadata:
  finalizers: []
  name: grafana
spec:
  image:
    image: docker.io/bitnami/grafana:7.5.6

  injector:
    enabled: false
    image:
      image: quay.io/elostech/grafana-injector:v0.72
    apiEndpoints:
      openshift:
        url: ""
        port: 6443
      grafana:
        url: http://localhost
        port: 3000
      git:
        url: ""
        protocol: https
    credentials:
      openshift:
        user: ""
        pass: ""
      grafana:
        user: ""
        pass: ""
      git:
        user: ""
        pass: ""
    timing:
     startDelay: 30
     interval: 300
    projects_labels_selector: monitoring.elostech.cz/create-grafana-folder=true
    pruneFolders: true

  oauthProxy:
    enabled: true
    image:
      image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:d9601f2660b45d005ba9526ea6e87cb837308d45a92c71c4ea3412e27ce0b0ec

  GenericOAuth:
  enabled: false
  name:
  clientId:
  clientSecret:
  authUrl:
  tokenUrl:
  apiUrl:
  TlsSkipVerifyInsecure: false

  admin:
    user: admin
    password: ""

  securityContext:
    enabled: false
    fsGroup: 0

  persistence:
    enabled: false

  datasources:
    config: |
      apiVersion: 1
      datasources:
        - name: Thanos
          type: prometheus
          access: proxy
          url: http://thanos-querier-frontend.${NAMESPACE}.svc.cluster.local:9090
          editable: false

  openshiftRoute:
    enabled: true
    host: "grafana.${APP_DOMAIN}"

  # Run on infra nodes:
  #nodeSelector:
  #  node-role.kubernetes.io/infra: ""
  #tolerations:
  #- key: infra
  #  value: reserved
  #  effect: NoSchedule
  #- key: infra
  #  value: reserved
  #  effect: NoExecute

  # Run on dedicated "monitoring" nodes:
  #nodeSelector:
  #  node-role.kubernetes.io/monitoring: ""
  #tolerations:
  #- key: "node-role"
  #  operator: "Equal"
  #  value: "monitoring"
  #  effect: "NoSchedule"

  metrics:
    enabled: true

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 256Mi  
