apiVersion: monitoring.elostech.cz/v1alpha1
kind: Pushgateway
metadata:
  finalizers: []
  name: pushgateway
spec:
  image:
    image: prom/pushgateway:v1.2.0

  openshiftRoute:
    enabled: false
    host: pushgateway.${APP_DOMAIN}

  # Run on infra nodes:
  #nodeSelector:
  #  node-role.kubernetes.io/infra: ""
  #tolerations:
  #- key: infra
  #  value: reserved
  #  effect: NoSchedule
  #- key: infra
  #  value: reserved
  #  effect: NoExecute

  # Run on dedicated "monitoring" nodes:
  #nodeSelector:
  #  node-role.kubernetes.io/monitoring: ""
  #tolerations:
  #- key: "node-role"
  #  operator: "Equal"
  #  value: "monitoring"
  #  effect: "NoSchedule"
