apiVersion: monitoring.elostech.cz/v1alpha1
kind: ThanosReceive
metadata:
  finalizers: []
  name: thanos-receive
spec:
  image:
    image: quay.io/thanos/thanos:v0.15.0

  objectStoreSecret:
    name: "thanos-objstore-secret"
    key: "objstore.yml"

  # Run on infra nodes:
  #nodeSelector:
  #  node-role.kubernetes.io/infra: ""
  #tolerations:
  #- key: infra
  #  value: reserved
  #  effect: NoSchedule
  #- key: infra
  #  value: reserved
  #  effect: NoExecute

  # Run on dedicated "monitoring" nodes:
  #nodeSelector:
  #  node-role.kubernetes.io/monitoring: ""
  #tolerations:
  #- key: "node-role"
  #  operator: "Equal"
  #  value: "monitoring"
  #  effect: "NoSchedule"

  persistence:
    enabled: ${PERSISTENCE_ENABLED}
    size: 30Gi
    storageClass: ${STORAGE_CLASS}

  openshiftRoute:
    enabled: true
    host: thanos-receive.${APP_DOMAIN}

  # Always use "receive_" for all labels defined here.
  # https://thanos.io/tip/thanos/storage.md/#external-labels
  labels:
    - receive_stack="erynis"

  resources:
    requests:
      memory: 5Gi
    limits:
      memory: 12Gi
