apiVersion: monitoring.elostech.cz/v1alpha1
kind: Thanos
metadata:
  finalizers: []
  name: thanos
spec:

  ### Object Storage

  # Directly defined here in CR.
  #
  # Minio:
  objstoreConfig: |-
    type: s3
    config:
      bucket: thanos
      endpoint: minio.erynis-monitoring.svc.cluster.local:9000
      access_key: minio
      secret_key: password123
      insecure: true

  # Azure:
  #objstoreConfig: |-
  #  type: AZURE
  #  config:
  #    storage_account: "..."
  #    storage_account_key: "..."
  #    container: "erynis-azure-blob"
  #    endpoint: "blob.core.windows.net"
  #    max_retries: 0

  # If external secret is used, uncomment this instead of objstoreConfig:
  #existingObjstoreSecret: ${OBJSTORE_SECRET_NAME}


  querier:
    #nodeSelector:
    #  node-role.kubernetes.io/monitoring: ""
    #tolerations:
    #- key: "node-role"
    #  operator: "Equal"
    #  value: "monitoring"
    #  effect: "NoSchedule"
    replicaLabel: prometheus_replica
    stores:
      - dnssrv+_grpc._tcp.thanos-receive.${NAMESPACE}.svc.cluster.local
    securityContext:
      enabled: false
      fsGroup: 0
    grpcTLS:
      client:
        secure: false
    openshiftRoute:
      enabled: true
      host: thanos-querier.${APP_DOMAIN}

  querierfrontend:
    enabled: true
    openshiftRoute:
      enabled: true
      httpsEnabled: true
      host: thanos-querier-frontend.${APP_DOMAIN}

  bucketweb:
    enabled: true
    #nodeSelector:
    #  node-role.kubernetes.io/monitoring: ""
    #tolerations:
    #- key: "node-role"
    #  operator: "Equal"
    #  value: "monitoring"
    #  effect: "NoSchedule"
    securityContext:
      enabled: false
      fsGroup: 0
    openshiftRoute:
      enabled: true
      host: thanos-bucketweb.${APP_DOMAIN}

  compactor:
    enabled: true
    #nodeSelector:
    #  node-role.kubernetes.io/monitoring: ""
    #tolerations:
    #- key: "node-role"
    #  operator: "Equal"
    #  value: "monitoring"
    #  effect: "NoSchedule"
    securityContext:
      enabled: false
      fsGroup: 0
    persistence:
      enabled: ${PERSISTENCE_ENABLED}
      size: 20Gi
      storageClass: ${STORAGE_CLASS}

  storegateway:
    enabled: true
    #nodeSelector:
    #  node-role.kubernetes.io/monitoring: ""
    #tolerations:
    #- key: "node-role"
    #  operator: "Equal"
    #  value: "monitoring"
    #  effect: "NoSchedule"
    securityContext:
      enabled: false
      fsGroup: 0
    persistence:
      enabled: ${PERSISTENCE_ENABLED}
      size: 20Gi
      storageClass: ${STORAGE_CLASS}

  ruler:
    enabled: true
    #nodeSelector:
    #  node-role.kubernetes.io/monitoring: ""
    #tolerations:
    #- key: "node-role"
    #  operator: "Equal"
    #  value: "monitoring"
    #  effect: "NoSchedule"
    securityContext:
      enabled: false
      fsGroup: 0
    persistence:
      enabled: ${PERSISTENCE_ENABLED}
      size: 20Gi
      storageClass: ${STORAGE_CLASS}
    alertmanagers:
      - http://alertmanager-operated.openshift-monitoring.svc.cluster.local:9093
    config: |-
      groups:
        - name: "metamonitoring"
          rules:
            - alert: "PrometheusDown"
              expr: absent(up{prometheus="openshift-monitoring/k8s",service="prometheus-k8s"})

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  minio:
    enabled: true
    openshiftRoute:
      enabled: true
      host: thanos-minio.${APP_DOMAIN}
    defaultBuckets: "thanos"
    persistence:
      enabled: ${PERSISTENCE_ENABLED}
      size: 100Gi
      storageClass: ${STORAGE_CLASS}

    # Minio Access Keys
    #
    # Directly in CR:
    accessKey:
      password: "minio"
    secretKey:
      password: "password123"

    # Or stored in existing secret:
    #existingSecret: ${MINIO_SECRET_NAME}

